# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2019-04-02 16:03
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations


def create_council_group(apps, schema_editor):
    Group = apps.get_model('auth', 'group')
    Group.objects.create(name='Council')


def destroy_council_group(apps, schema_editor):
    Group = apps.get_model('auth', 'group')
    group = Group.objects.filter(name='Council')
    group.delete()

PAGES = [
    {'title': 'About Bioluminati', 'url': '/about/',
    'content': """
    <i><b>elucido solitudo obscurum - to light the desert's darkness</b></i>

    <h1>Who are we?</h1>

    <p>Bioluminati is a theme camp at Burning Man. We are a merry group of ~35 people with mixed backgrounds; primarily in technology and the arts. We thrive by cooperative effort and bond around our fine cuisine. About 120 Burners have joined us at one time or another over the years, so far hailing from the United States, Canada, England, and Germany.</p>
    <p>Bioluminati is a 501(c)(7) tax exempt, not-for-profit, organization, incorporated in the state of California.  Its purpose is to coordinate the camp infrastructure, transportation logistics, costs and management. We own a cargo trailer that stores most of our physical infrastructure when we are not on the Playa.  We also own a large cargo truck for storage and transport of whatever needs to be maintained after each Burn.</p>
    <p>We have been an active camp since 1996. In the early years, we primarily focused on Bio-illumination. This involved many glowsticks, the common personal lighting at the time. With the advent of cheap EL-wire and LED lighting, many on the playa are now well lit.
    </p>
    <p>The camp has also had various interactive art projects, as well as Quests involving all of Black Rock City.</p>
    <p>In 2005, campers Nick and Tracy had an idea- offer to the city some form of bike decoration station. From this idea, Pimp Your Bike began, and made its debut at Burning Man 2006. It has evolved into a popular offering with growing success. All our campers are expected to contribute.  We utilize donations of all manner of odd non-"MOOP" producing items - old xmas ornaments, paint, stickers, found objects, led lights and fabric - for fellow playa citizens to dress up their rides!</p>
    <p>
    In 2007, camper Random started Micro-Cinema: a nightly projection of camper's and friend's video projects. These are interlaced with non-mainstream personal movie favorites.</p>
    <p>Feel free to browse our site. Look at our photos, learn about our shelters, check out our awesome kitchen system and some of our crazy ideas!</p>
        """},
    {'title': 'homepage', 'url': '/home/', 'content': """
    <p>Bioluminati has camped on Playa for over 20 years.  We offer bike decorating facilities known as Bike Mutation Station (BMS) and Pimp Your Bike.</p>
    <p>We welcome campers of all backgrounds.  >>> TK copy about values and culture.</p>
    <p>Our camp invests in shared infrastructure, including large common-area shelters, kitchen, shower, fire pit, group meals and dining area, and a pooled bikes for shared use.</p>
    <p>To make this possible, all campers are expected to sign up for work shifts, such as meal prep, BMS, setup or teardown.</p>
    <p>First-time campers must be sponsored by existing campers.  This way we ensure people joining feel welcomed and included.</p>
    """},
    {'title': 'Preparing', 'url': '/prep/', 'content': """
    <p> If you're new to the Burn, it's a good idea to spend some time reading up on how to prepare and what to expect. </p>
    <p>
    At the very minimum, please read the official website's <a href="http://burningman.org/event/preparation/first-timers-guide/">first timer's guide</a>, including the packing list and review of the ten principles.  Both of these are critical to thriving in the harsh environment, and to being a good citizen at Black Rock City.
    </p>
    <p>
    Burning Man can be an overwhelming experience, and the <a href="https://www.fest300.com/magazine/an-emotional-survival-guide-to-burning-man"> Emotional Survival Guide</a> is a handy guide for considering some of the other parts of thriving in this overwhelming and challenging context. If you're bringing kids, there's a handy guide that the org prepared you can get <a href="http://burningman.org/event/preparation/playa-living/kids/"> here.</a>
    </p>
    <p>
    Finally, there's always the <a href="https://www.reddit.com/r/burningman">Burning Man Reddit community</a> where you can find answers to all sorts of questions, and of course, our group list for general advice is always a good place to start.
    </p>
    """}
]

def create_pages(apps, schema_editor):
    FlatPage = apps.get_model('flatpages', 'flatpage')
    for page in PAGES:
        f = FlatPage.objects.create(**page)
        f.sites.add(1)


def destroy_pages(apps, schema_editor):
    FlatPage = apps.get_model('flatpages', 'flatpage')
    FlatPage.objects.filter(title__in=[p['title'] for p in PAGES]).delete()


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('flatpages', '__first__'),
        ('camp', '0019_auto_20190402_1602'),
    ]

    operations = [
        migrations.RunPython(create_council_group, destroy_council_group),
        migrations.RunPython(create_pages, destroy_pages)
    ]
